# Generated by Django 4.2.20 on 2025-04-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='', max_length=10)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('course', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
