# Generated by Django 4.2.20 on 2025-04-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='interest',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
